"""
Cross-Language Parity Test for Reflex Compiled Models (Phase 25).
Verifies that a .reflex binary model generated by Python compiles and evaluates
with identical decision results in both Python and the Node.js / Edge SDK (@reflex-ai/sdk).
Zero external dependencies (Python standard library & Node.js built-ins only).
"""

import json
import os
import shutil
import subprocess
import tempfile
import unittest

from reflex.compiler import PromptSpec, InstinctCompiler, CompiledInstinct


class TestCrossLanguageCompiler(unittest.TestCase):
    """Verifies that .reflex artifacts load and execute with parity across Python and Node.js."""

    @classmethod
    def setUpClass(cls):
        cls.temp_file = tempfile.NamedTemporaryFile(suffix=".reflex", delete=False)
        cls.model_path = cls.temp_file.name
        cls.temp_file.close()

        # 1. Compile a multi-class model in Python
        spec = PromptSpec(
            prompt="Triage customer tickets into billing, technical, or sales queues",
            decision_type="choice",
            options=["billing", "technical", "sales"],
            guidelines={
                "billing": "Invoice charges, payments, credit card renewal, VAT receipts, refunds",
                "technical": "Server down, 500 error, memory leak, API timeout, crash, database failure",
                "sales": "Enterprise volume pricing, seat upgrade, demo scheduling, annual contract quote",
            },
            name="cross_lang_triage",
        )
        compiler = InstinctCompiler()
        cls.model = compiler.compile(spec, samples_per_class=20, epochs=25)
        cls.model.save(cls.model_path)

    @classmethod
    def tearDownClass(cls):
        if os.path.exists(cls.model_path):
            os.unlink(cls.model_path)

    def test_python_and_nodejs_parity(self):
        node_bin = shutil.which("node")
        if not node_bin:
            self.skipTest("Node.js not installed on system")

        sdk_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "packages", "reflex-sdk", "index.js"))

        test_queries = [
            "Why was my credit card charged twice for the renewal invoice?",
            "Production server is returning HTTP 504 gateway timeout on database queries",
            "We have 150 engineers and want to discuss enterprise pricing discounts",
            "Can I get a copy of last month's VAT receipt for tax accounting?",
            "API endpoint crashes intermittently with an unhandled exception",
        ]

        # 1. Python predictions
        py_results = []
        for q in test_queries:
            pred = self.model.predict(q)
            py_results.append({
                "query": q,
                "selected": pred["choice"].selected,
                "distribution": pred["choice"].distribution,
            })

        # 2. Node.js predictions using @reflex-ai/sdk
        node_script = f"""
import fs from 'node:fs';
import {{ CompiledInstinct }} from '{sdk_path}';

const buffer = fs.readFileSync('{self.model_path}');
const model = CompiledInstinct.fromBinary(buffer);
const queries = {json.dumps(test_queries)};

const results = queries.map(q => {{
    const res = model.predict(q);
    return {{
        query: q,
        selected: res.decisions.choice.selected,
        distribution: res.decisions.choice.distribution
    }};
}});

console.log(JSON.stringify(results));
"""
        proc = subprocess.run(
            [node_bin, "--input-type=module", "-e", node_script],
            capture_output=True,
            text=True,
            check=True,
        )
        node_results = json.loads(proc.stdout.strip())

        self.assertEqual(len(py_results), len(node_results))

        # 3. Assert mathematical agreement
        for py_res, js_res in zip(py_results, node_results):
            self.assertEqual(
                py_res["selected"],
                js_res["selected"],
                f"Prediction mismatch for query '{py_res['query']}': Python={py_res['selected']}, Node={js_res['selected']}"
            )
            # Verify probability distribution agreement
            for opt in ["billing", "technical", "sales"]:
                p_py = py_res["distribution"].get(opt, 0.0)
                p_js = js_res["distribution"].get(opt, 0.0)
                self.assertAlmostEqual(
                    p_py, p_js, delta=0.05,
                    msg=f"Distribution mismatch on '{opt}' for query '{py_res['query']}': Python={p_py}, Node={p_js}"
                )

    def test_python_and_rust_parity(self):
        cargo_bin = shutil.which("cargo")
        if not cargo_bin:
            self.skipTest("Cargo not installed on system")

        cargo_toml = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "packages", "reflex-rs", "Cargo.toml"))

        test_queries = [
            "Why was my credit card charged twice for the renewal invoice?",
            "Production server is returning HTTP 504 gateway timeout on database queries",
            "We have 150 engineers and want to discuss enterprise pricing discounts",
            "Can I get a copy of last month's VAT receipt for tax accounting?",
            "API endpoint crashes intermittently with an unhandled exception",
        ]

        # 1. Python predictions
        py_results = []
        for q in test_queries:
            pred = self.model.predict(q)
            py_results.append({
                "query": q,
                "selected": pred["choice"].selected,
                "distribution": pred["choice"].distribution,
            })

        # 2. Rust predictions using reflex-rs compiled_parity
        cmd = [
            cargo_bin, "run", "--quiet", "--manifest-path", cargo_toml,
            "--example", "compiled_parity", "--", self.model_path
        ] + test_queries

        proc = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            check=True,
        )
        rust_results = json.loads(proc.stdout.strip())

        self.assertEqual(len(py_results), len(rust_results))

        # 3. Assert mathematical agreement
        for py_res, rust_res in zip(py_results, rust_results):
            self.assertEqual(
                py_res["selected"],
                rust_res["selected"],
                f"Prediction mismatch for query '{py_res['query']}': Python={py_res['selected']}, Rust={rust_res['selected']}"
            )
            for opt in ["billing", "technical", "sales"]:
                p_py = py_res["distribution"].get(opt, 0.0)
                p_rust = rust_res["distribution"].get(opt, 0.0)
                self.assertAlmostEqual(
                    p_py, p_rust, delta=0.05,
                    msg=f"Distribution mismatch on '{opt}' for query '{py_res['query']}': Python={p_py}, Rust={p_rust}"
                )


if __name__ == "__main__":
    unittest.main()

